const ExcelJS = require('exceljs');

/**
 * Export issued reports to an Excel (.xlsx) buffer
 * @param {Array} rows - array of report row objects
 * @param {Object} filters - { type, from, to } for sheet metadata
 * @returns {Buffer}
 */
const exportReportsToExcel = async (rows, filters = {}) => {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'InvenCEA';
  workbook.created = new Date();

  const sheet = workbook.addWorksheet('Issued Reports', {
    pageSetup: { paperSize: 9, orientation: 'landscape' },
  });

  // Column definitions
  sheet.columns = [
    { header: 'Request ID', key: 'request_id', width: 12 },
    { header: 'Requester Type', key: 'requester_type', width: 16 },
    { header: 'Requester Name', key: 'requester_name', width: 24 },
    { header: 'Room', key: 'room_code', width: 12 },
    { header: 'Item Name', key: 'item_name', width: 28 },
    { header: 'Barcode', key: 'barcode', width: 16 },
    { header: 'Quantity', key: 'quantity', width: 10 },
    { header: 'Requested Time', key: 'requested_time', width: 22 },
    { header: 'Approved Time', key: 'approved_time', width: 22 },
    { header: 'Issued Time', key: 'issued_time', width: 22 },
    { header: 'Status', key: 'status', width: 12 },
  ];

  // Header styling
  const headerRow = sheet.getRow(1);
  headerRow.eachCell((cell) => {
    cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1F4E79' } };
    cell.alignment = { vertical: 'middle', horizontal: 'center' };
    cell.border = {
      bottom: { style: 'thin', color: { argb: 'FF000000' } },
    };
  });
  headerRow.height = 20;

  // Data rows
  rows.forEach((row, idx) => {
    const dataRow = sheet.addRow({
      request_id: row.request_id,
      requester_type: row.requester_type,
      requester_name: row.requester_name || '',
      room_code: row.room_code || '',
      item_name: row.item_name || '',
      barcode: row.barcode || '',
      quantity: row.quantity || 1,
      requested_time: row.requested_time ? new Date(row.requested_time).toLocaleString() : '',
      approved_time: row.approved_time ? new Date(row.approved_time).toLocaleString() : '',
      issued_time: row.issued_time ? new Date(row.issued_time).toLocaleString() : '',
      status: row.status || '',
    });

    // Alternating row color
    if (idx % 2 === 1) {
      dataRow.eachCell((cell) => {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE8F0FE' } };
      });
    }
  });

  // Auto-filter on header row
  sheet.autoFilter = {
    from: { row: 1, column: 1 },
    to: { row: 1, column: sheet.columns.length },
  };

  // Freeze top row
  sheet.views = [{ state: 'frozen', ySplit: 1 }];

  // Metadata sheet
  const metaSheet = workbook.addWorksheet('Export Info');
  metaSheet.addRow(['Generated By', 'InvenCEA System']);
  metaSheet.addRow(['Export Date', new Date().toLocaleString()]);
  metaSheet.addRow(['Filter Type', filters.type || 'all']);
  metaSheet.addRow(['Date From', filters.from || '-']);
  metaSheet.addRow(['Date To', filters.to || '-']);
  metaSheet.addRow(['Total Rows', rows.length]);

  const buffer = await workbook.xlsx.writeBuffer();
  return buffer;
};

module.exports = { exportReportsToExcel };
